// flow-typed signature: f502971fb3901c08e3a89c7e95185926
// flow-typed version: <<STUB>>/@vitest/coverage-v8_v^1.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vitest/coverage-v8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vitest/coverage-v8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vitest/coverage-v8/dist' {
  declare module.exports: any;
}

declare module '@vitest/coverage-v8/dist/provider' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vitest/coverage-v8/dist/index' {
  declare module.exports: $Exports<'@vitest/coverage-v8/dist'>;
}
declare module '@vitest/coverage-v8/dist/index.js' {
  declare module.exports: $Exports<'@vitest/coverage-v8/dist'>;
}
declare module '@vitest/coverage-v8/dist/provider.js' {
  declare module.exports: $Exports<'@vitest/coverage-v8/dist/provider'>;
}
