// flow-typed signature: 545052d5f54cefc3c8ff1ab9ab1f7e28
// flow-typed version: <<STUB>>/bowser_v^2.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bowser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bowser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bowser/bundled' {
  declare module.exports: any;
}

declare module 'bowser/es5' {
  declare module.exports: any;
}

declare module 'bowser/src/bowser' {
  declare module.exports: any;
}

declare module 'bowser/src/constants' {
  declare module.exports: any;
}

declare module 'bowser/src/parser-browsers' {
  declare module.exports: any;
}

declare module 'bowser/src/parser-engines' {
  declare module.exports: any;
}

declare module 'bowser/src/parser-os' {
  declare module.exports: any;
}

declare module 'bowser/src/parser-platforms' {
  declare module.exports: any;
}

declare module 'bowser/src/parser' {
  declare module.exports: any;
}

declare module 'bowser/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bowser/bundled.js' {
  declare module.exports: $Exports<'bowser/bundled'>;
}
declare module 'bowser/es5.js' {
  declare module.exports: $Exports<'bowser/es5'>;
}
declare module 'bowser/src/bowser.js' {
  declare module.exports: $Exports<'bowser/src/bowser'>;
}
declare module 'bowser/src/constants.js' {
  declare module.exports: $Exports<'bowser/src/constants'>;
}
declare module 'bowser/src/parser-browsers.js' {
  declare module.exports: $Exports<'bowser/src/parser-browsers'>;
}
declare module 'bowser/src/parser-engines.js' {
  declare module.exports: $Exports<'bowser/src/parser-engines'>;
}
declare module 'bowser/src/parser-os.js' {
  declare module.exports: $Exports<'bowser/src/parser-os'>;
}
declare module 'bowser/src/parser-platforms.js' {
  declare module.exports: $Exports<'bowser/src/parser-platforms'>;
}
declare module 'bowser/src/parser.js' {
  declare module.exports: $Exports<'bowser/src/parser'>;
}
declare module 'bowser/src/utils.js' {
  declare module.exports: $Exports<'bowser/src/utils'>;
}
