// flow-typed signature: f1900fef0f6ee28f6a550d1295058842
// flow-typed version: <<STUB>>/cheerio_v1.0.0-rc.9/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cheerio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cheerio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cheerio/lib/api/attributes' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/css' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/forms' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/manipulation' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/traversing' {
  declare module.exports: any;
}

declare module 'cheerio/lib/cheerio' {
  declare module.exports: any;
}

declare module 'cheerio/lib' {
  declare module.exports: any;
}

declare module 'cheerio/lib/load' {
  declare module.exports: any;
}

declare module 'cheerio/lib/options' {
  declare module.exports: any;
}

declare module 'cheerio/lib/parse' {
  declare module.exports: any;
}

declare module 'cheerio/lib/parsers/htmlparser2' {
  declare module.exports: any;
}

declare module 'cheerio/lib/parsers/parse5' {
  declare module.exports: any;
}

declare module 'cheerio/lib/static' {
  declare module.exports: any;
}

declare module 'cheerio/lib/types' {
  declare module.exports: any;
}

declare module 'cheerio/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cheerio/lib/api/attributes.js' {
  declare module.exports: $Exports<'cheerio/lib/api/attributes'>;
}
declare module 'cheerio/lib/api/css.js' {
  declare module.exports: $Exports<'cheerio/lib/api/css'>;
}
declare module 'cheerio/lib/api/forms.js' {
  declare module.exports: $Exports<'cheerio/lib/api/forms'>;
}
declare module 'cheerio/lib/api/manipulation.js' {
  declare module.exports: $Exports<'cheerio/lib/api/manipulation'>;
}
declare module 'cheerio/lib/api/traversing.js' {
  declare module.exports: $Exports<'cheerio/lib/api/traversing'>;
}
declare module 'cheerio/lib/cheerio.js' {
  declare module.exports: $Exports<'cheerio/lib/cheerio'>;
}
declare module 'cheerio/lib/index' {
  declare module.exports: $Exports<'cheerio/lib'>;
}
declare module 'cheerio/lib/index.js' {
  declare module.exports: $Exports<'cheerio/lib'>;
}
declare module 'cheerio/lib/load.js' {
  declare module.exports: $Exports<'cheerio/lib/load'>;
}
declare module 'cheerio/lib/options.js' {
  declare module.exports: $Exports<'cheerio/lib/options'>;
}
declare module 'cheerio/lib/parse.js' {
  declare module.exports: $Exports<'cheerio/lib/parse'>;
}
declare module 'cheerio/lib/parsers/htmlparser2.js' {
  declare module.exports: $Exports<'cheerio/lib/parsers/htmlparser2'>;
}
declare module 'cheerio/lib/parsers/parse5.js' {
  declare module.exports: $Exports<'cheerio/lib/parsers/parse5'>;
}
declare module 'cheerio/lib/static.js' {
  declare module.exports: $Exports<'cheerio/lib/static'>;
}
declare module 'cheerio/lib/types.js' {
  declare module.exports: $Exports<'cheerio/lib/types'>;
}
declare module 'cheerio/lib/utils.js' {
  declare module.exports: $Exports<'cheerio/lib/utils'>;
}
