// flow-typed signature: 0e3be2fa66f84bc85d9ce070fc4b08e0
// flow-typed version: <<STUB>>/vitest_v^1.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vitest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vitest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vitest/dist/browser' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/api-setup.omeaEsoT' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/install-pkg.LE8oaA1t' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/integrations-globals.9QpVy4UR' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/node-git.Hw101KjS' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/runtime-console.Iloo9fIt' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/runtime-runBaseTests.S8ZSFig3' {
  declare module.exports: any;
}

declare module 'vitest/dist/cli-wrapper' {
  declare module.exports: any;
}

declare module 'vitest/dist/cli' {
  declare module.exports: any;
}

declare module 'vitest/dist/config' {
  declare module.exports: any;
}

declare module 'vitest/dist/coverage' {
  declare module.exports: any;
}

declare module 'vitest/dist/environments' {
  declare module.exports: any;
}

declare module 'vitest/dist/execute' {
  declare module.exports: any;
}

declare module 'vitest/dist' {
  declare module.exports: any;
}

declare module 'vitest/dist/node' {
  declare module.exports: any;
}

declare module 'vitest/dist/path' {
  declare module.exports: any;
}

declare module 'vitest/dist/reporters' {
  declare module.exports: any;
}

declare module 'vitest/dist/runners' {
  declare module.exports: any;
}

declare module 'vitest/dist/spy' {
  declare module.exports: any;
}

declare module 'vitest/dist/suite' {
  declare module.exports: any;
}

declare module 'vitest/dist/utils' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/_commonjsHelpers.jjO7Zipk' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/base.4sEqnqgY' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/base.QYERqzkH' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/benchmark.IlKmJkUU' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/constants.i1PoEnhr' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/coverage.E7sG1b3r' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/date.Ns1pGd_X' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/environments.sU0TD7wX' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/execute.edwByI27' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/global.CkGT_TMy' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/index.cAUulNDf' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/index.kwCLJK4i' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/index.rJjbcrrp' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/index.vs_-lzuF' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/index.xL8XjTLv' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/node.p6h5JSuL' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/reporters.cA9x-5v-' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/rpc.w4v8oCkK' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/run-once.Olz_Zkd8' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/setup-common.4GIL70qB' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/tasks.IknbGB2n' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/utils.GbToHGHI' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/vi.Bw2UL9c9' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor/vm.9N6CwTZh' {
  declare module.exports: any;
}

declare module 'vitest/dist/worker' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/forks' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/runVmTests' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/threads' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/vmForks' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/vmThreads' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vitest/dist/browser.js' {
  declare module.exports: $Exports<'vitest/dist/browser'>;
}
declare module 'vitest/dist/chunks/api-setup.omeaEsoT.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/api-setup.omeaEsoT'>;
}
declare module 'vitest/dist/chunks/install-pkg.LE8oaA1t.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/install-pkg.LE8oaA1t'>;
}
declare module 'vitest/dist/chunks/integrations-globals.9QpVy4UR.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/integrations-globals.9QpVy4UR'>;
}
declare module 'vitest/dist/chunks/node-git.Hw101KjS.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/node-git.Hw101KjS'>;
}
declare module 'vitest/dist/chunks/runtime-console.Iloo9fIt.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/runtime-console.Iloo9fIt'>;
}
declare module 'vitest/dist/chunks/runtime-runBaseTests.S8ZSFig3.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/runtime-runBaseTests.S8ZSFig3'>;
}
declare module 'vitest/dist/cli-wrapper.js' {
  declare module.exports: $Exports<'vitest/dist/cli-wrapper'>;
}
declare module 'vitest/dist/cli.js' {
  declare module.exports: $Exports<'vitest/dist/cli'>;
}
declare module 'vitest/dist/config.js' {
  declare module.exports: $Exports<'vitest/dist/config'>;
}
declare module 'vitest/dist/coverage.js' {
  declare module.exports: $Exports<'vitest/dist/coverage'>;
}
declare module 'vitest/dist/environments.js' {
  declare module.exports: $Exports<'vitest/dist/environments'>;
}
declare module 'vitest/dist/execute.js' {
  declare module.exports: $Exports<'vitest/dist/execute'>;
}
declare module 'vitest/dist/index' {
  declare module.exports: $Exports<'vitest/dist'>;
}
declare module 'vitest/dist/index.js' {
  declare module.exports: $Exports<'vitest/dist'>;
}
declare module 'vitest/dist/node.js' {
  declare module.exports: $Exports<'vitest/dist/node'>;
}
declare module 'vitest/dist/path.js' {
  declare module.exports: $Exports<'vitest/dist/path'>;
}
declare module 'vitest/dist/reporters.js' {
  declare module.exports: $Exports<'vitest/dist/reporters'>;
}
declare module 'vitest/dist/runners.js' {
  declare module.exports: $Exports<'vitest/dist/runners'>;
}
declare module 'vitest/dist/spy.js' {
  declare module.exports: $Exports<'vitest/dist/spy'>;
}
declare module 'vitest/dist/suite.js' {
  declare module.exports: $Exports<'vitest/dist/suite'>;
}
declare module 'vitest/dist/utils.js' {
  declare module.exports: $Exports<'vitest/dist/utils'>;
}
declare module 'vitest/dist/vendor/_commonjsHelpers.jjO7Zipk.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/_commonjsHelpers.jjO7Zipk'>;
}
declare module 'vitest/dist/vendor/base.4sEqnqgY.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/base.4sEqnqgY'>;
}
declare module 'vitest/dist/vendor/base.QYERqzkH.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/base.QYERqzkH'>;
}
declare module 'vitest/dist/vendor/benchmark.IlKmJkUU.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/benchmark.IlKmJkUU'>;
}
declare module 'vitest/dist/vendor/constants.i1PoEnhr.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/constants.i1PoEnhr'>;
}
declare module 'vitest/dist/vendor/coverage.E7sG1b3r.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/coverage.E7sG1b3r'>;
}
declare module 'vitest/dist/vendor/date.Ns1pGd_X.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/date.Ns1pGd_X'>;
}
declare module 'vitest/dist/vendor/environments.sU0TD7wX.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/environments.sU0TD7wX'>;
}
declare module 'vitest/dist/vendor/execute.edwByI27.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/execute.edwByI27'>;
}
declare module 'vitest/dist/vendor/global.CkGT_TMy.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/global.CkGT_TMy'>;
}
declare module 'vitest/dist/vendor/index.cAUulNDf.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/index.cAUulNDf'>;
}
declare module 'vitest/dist/vendor/index.kwCLJK4i.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/index.kwCLJK4i'>;
}
declare module 'vitest/dist/vendor/index.rJjbcrrp.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/index.rJjbcrrp'>;
}
declare module 'vitest/dist/vendor/index.vs_-lzuF.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/index.vs_-lzuF'>;
}
declare module 'vitest/dist/vendor/index.xL8XjTLv.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/index.xL8XjTLv'>;
}
declare module 'vitest/dist/vendor/node.p6h5JSuL.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/node.p6h5JSuL'>;
}
declare module 'vitest/dist/vendor/reporters.cA9x-5v-.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/reporters.cA9x-5v-'>;
}
declare module 'vitest/dist/vendor/rpc.w4v8oCkK.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/rpc.w4v8oCkK'>;
}
declare module 'vitest/dist/vendor/run-once.Olz_Zkd8.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/run-once.Olz_Zkd8'>;
}
declare module 'vitest/dist/vendor/setup-common.4GIL70qB.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/setup-common.4GIL70qB'>;
}
declare module 'vitest/dist/vendor/tasks.IknbGB2n.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/tasks.IknbGB2n'>;
}
declare module 'vitest/dist/vendor/utils.GbToHGHI.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/utils.GbToHGHI'>;
}
declare module 'vitest/dist/vendor/vi.Bw2UL9c9.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/vi.Bw2UL9c9'>;
}
declare module 'vitest/dist/vendor/vm.9N6CwTZh.js' {
  declare module.exports: $Exports<'vitest/dist/vendor/vm.9N6CwTZh'>;
}
declare module 'vitest/dist/worker.js' {
  declare module.exports: $Exports<'vitest/dist/worker'>;
}
declare module 'vitest/dist/workers.js' {
  declare module.exports: $Exports<'vitest/dist/workers'>;
}
declare module 'vitest/dist/workers/forks.js' {
  declare module.exports: $Exports<'vitest/dist/workers/forks'>;
}
declare module 'vitest/dist/workers/runVmTests.js' {
  declare module.exports: $Exports<'vitest/dist/workers/runVmTests'>;
}
declare module 'vitest/dist/workers/threads.js' {
  declare module.exports: $Exports<'vitest/dist/workers/threads'>;
}
declare module 'vitest/dist/workers/vmForks.js' {
  declare module.exports: $Exports<'vitest/dist/workers/vmForks'>;
}
declare module 'vitest/dist/workers/vmThreads.js' {
  declare module.exports: $Exports<'vitest/dist/workers/vmThreads'>;
}
