// flow-typed signature: c11ad434b38723cd77dc94b8e5d8e952
// flow-typed version: <<STUB>>/vite_v^4.0.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite/bin/vite' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-52909643' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-6e48fc1c' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-b0b3f1e6' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-c423598f' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-f0c7dae0' {
  declare module.exports: any;
}

declare module 'vite/dist/node/cli' {
  declare module.exports: any;
}

declare module 'vite/dist/node/constants' {
  declare module.exports: any;
}

declare module 'vite/dist/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite/bin/vite.js' {
  declare module.exports: $Exports<'vite/bin/vite'>;
}
declare module 'vite/dist/node/chunks/dep-52909643.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-52909643'>;
}
declare module 'vite/dist/node/chunks/dep-6e48fc1c.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-6e48fc1c'>;
}
declare module 'vite/dist/node/chunks/dep-b0b3f1e6.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-b0b3f1e6'>;
}
declare module 'vite/dist/node/chunks/dep-c423598f.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-c423598f'>;
}
declare module 'vite/dist/node/chunks/dep-f0c7dae0.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-f0c7dae0'>;
}
declare module 'vite/dist/node/cli.js' {
  declare module.exports: $Exports<'vite/dist/node/cli'>;
}
declare module 'vite/dist/node/constants.js' {
  declare module.exports: $Exports<'vite/dist/node/constants'>;
}
declare module 'vite/dist/node/index' {
  declare module.exports: $Exports<'vite/dist/node'>;
}
declare module 'vite/dist/node/index.js' {
  declare module.exports: $Exports<'vite/dist/node'>;
}
