// flow-typed signature: 03be0f79d6d4d30c0285475d481214e6
// flow-typed version: <<STUB>>/@krakenjs/babel-config-grumbler_v^8.1.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/babel-config-grumbler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/babel-config-grumbler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/babel-config-grumbler/babelrc-browser' {
  declare module.exports: any;
}

declare module '@krakenjs/babel-config-grumbler/babelrc-node' {
  declare module.exports: any;
}

declare module '@krakenjs/babel-config-grumbler/flow-ts-babel-preset' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/babel-config-grumbler/babelrc-browser.js' {
  declare module.exports: $Exports<'@krakenjs/babel-config-grumbler/babelrc-browser'>;
}
declare module '@krakenjs/babel-config-grumbler/babelrc-node.js' {
  declare module.exports: $Exports<'@krakenjs/babel-config-grumbler/babelrc-node'>;
}
declare module '@krakenjs/babel-config-grumbler/flow-ts-babel-preset.js' {
  declare module.exports: $Exports<'@krakenjs/babel-config-grumbler/flow-ts-babel-preset'>;
}
