// flow-typed signature: ad4e504a4b182585d03ee0d03946a5e6
// flow-typed version: <<STUB>>/@krakenjs/eslint-config-grumbler_v^8.1.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/eslint-config-grumbler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/eslint-config-grumbler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/eslint-config-grumbler/eslint' {
  declare module.exports: any;
}

declare module '@krakenjs/eslint-config-grumbler/eslintrc-browser' {
  declare module.exports: any;
}

declare module '@krakenjs/eslint-config-grumbler/eslintrc-browser.test' {
  declare module.exports: any;
}

declare module '@krakenjs/eslint-config-grumbler/eslintrc-node' {
  declare module.exports: any;
}

declare module '@krakenjs/eslint-config-grumbler/eslintrc-typescript' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/eslint-config-grumbler/eslint.js' {
  declare module.exports: $Exports<'@krakenjs/eslint-config-grumbler/eslint'>;
}
declare module '@krakenjs/eslint-config-grumbler/eslintrc-browser.js' {
  declare module.exports: $Exports<'@krakenjs/eslint-config-grumbler/eslintrc-browser'>;
}
declare module '@krakenjs/eslint-config-grumbler/eslintrc-browser.test.js' {
  declare module.exports: $Exports<'@krakenjs/eslint-config-grumbler/eslintrc-browser.test'>;
}
declare module '@krakenjs/eslint-config-grumbler/eslintrc-node.js' {
  declare module.exports: $Exports<'@krakenjs/eslint-config-grumbler/eslintrc-node'>;
}
declare module '@krakenjs/eslint-config-grumbler/eslintrc-typescript.js' {
  declare module.exports: $Exports<'@krakenjs/eslint-config-grumbler/eslintrc-typescript'>;
}
